services:
  fastapi-template:
    image: fastapi-template
    container_name: fastapi-template
    expose:
      - 8000
    ports:
      - "8000:8000"
    command:
      - --reload
    env_file:
      - ../.env
    volumes:
      - ../:/backend/fastapi-template
    depends_on:
      fastapi-template-db:
        condition: service_healthy

  fastapi-template-db:
    image: postgres:17-alpine
    container_name: fastapi-template-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fastapi-template
      POSTGRES_PASSWORD: fastapi-template-password
      POSTGRES_DB: fastapi-template
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U fastapi-template -d fastapi-template-db" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 50

volumes:
  postgres_data:
